### ISSUE TITLE
TRUE & FALSE not defined

### ISSUE THREAD

**Issue by pengan1990** [ApsaraDB/galaxyengine#1]
You have lost you TRUE AND FALSE defined in my_global.h file 

#ifndef MY_GLOBAL_INCLUDED
#define MY_GLOBAL_INCLUDED

/* Define some general constants */
#ifndef TRUE
#define TRUE		         (1)	/* Logical true */
#define FALSE		(0)	/* Logical false */
#endif

#endif  // MY_GLOBAL_INCLUDED

**Comment by xpchild** [comment]
We have fixed the build error,  reopen it if any problem again.
