### ISSUE TITLE
Error reported when using rpmbuild: Cannot find /sql/sql_yacc.h

### ISSUE THREAD

**Issue by as71469837** [ApsaraDB/galaxyengine#43]
Operating System: KylinOS V10
When using rpmbuild-bb t-polardbx-engine. spec to create, an error occurs with the prompt:   Cannot find /opt/polardbx/polardbx-engine-2.4.1/sql/sql_yacc.h
![image](https://github.com/user-attachments/assets/c1ca2860-138a-4e79-9859-2a0f5c3d4fb4)

**Comment by Spider4U** [comment]
Same Error: Cannot find /opt/polardbx/polardbx-engine-2.4.2/sql/sql_yacc.h
How to fix it @as71469837
